Info:     Reading ABAQUS from C:/Users/yfsun/PycharmProjects/NextEval/NextExchange/case1/nle1xf3c.inp using C:\Program Files\Altair\2025\hwdesktop\io\model_readers\feinput\bin\win64\abaqus.exe on 04-21-2025 21:18:12.
Info:     Processing Modules.
Info:     Processing Cards.
Info:     Processing System Collectors.
Info:     Processing Systems.
Info:     Processing Nodes.
Info:     Processing Materials.
Info:     Processing Properties.
Info:     Processing Components.
Info:     Processing Groups.
Info:     Processing Elements.
Info:     Processing Load Collectors.
Info:     Processing Equations.
Info:     Processing Loads.
Info:     Processing Assemblies.
Info:     Processing Curves.
Info:     Processing Plots.
Info:     Processing Sets.
Info:     Processing Output Blocks.
Info:     Processing Load Steps.
Info:     Processing Plys.
Info:     Processing Laminates.
Info:     Processing Beamsectcols.
Info:     Processing Beamsections.
Info:     Processing Optitableentrs.
Info:     Processing Tags.
Info:     Processing Contactsurfs.
Info:     Processing Joints.
Info:     Processing Mechanismconstraints.
Info:     Processing Boxes.
Info:     Processing Crosssections.
Info:     Processing Rigidbodies.
Info:     Processing Bodies.
Info:     Processing Mechanisms.
Info:     Processing Transformations.
Info:     Processing Positions.
Info:     Processing Contactgroups.
Info:     Processing Solvermasses.
Info:     Processing Comments.
Info:     Processing Constraints.
Info:     Processing Parameters.

Summary:  Feinput finished with 0 errors and 0 warnings.
Info:     Translation Complete.
